---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hello-kubernetes
  namespace: flux-system
spec:
  image: index.docker.io/jsaraswathi/flux-example
  interval: 1m0s
